GetResultsExpectiles <- function(coords = c(lon,lat)) {
  #the input argument is a vector of dimension 2, speciying a longitude and latitude coordinate
  #set working directory
  setwd('')
  
  #load packages
  library(car)
  
  #name the entrys of the input vector for easier handling
  lon <- coords[1]
  lat <- coords[2]
  
  #load the result file generated by EstimateExpectiles for the respective coordinates
  load(paste0('Daten/Ergebnisse/Expectiles_new/Expectile_preD_TRMM_025_025_ECMWF_24_1998-2017_'
              ,lon, '_',lat,'.Rdata'))
  
  ##Extract the results from the result dataframe
  #Theta
  theta_1_q <- res_expectiles$theta[[1]]
  theta_2_q <- res_expectiles$theta[[2]]
  
  #Pvalue JTest
  helpvar <- summary(res_expectiles$Res)
  pvalue <- helpvar$Jtest$test[1,2]
  
  #Pvalue Wald
  #out <- tryCatch({
  #  gmm <- res_expectiles$Res$gmm
  #  pWald <- linearHypothesis(gmm, 'Theta[2]=0')
  #  return(pWald[2,3])
  #}, error = function(cond) {
  #  message(cond)
  #  pWald <- NaN
  #  return(pWald)
  #}, warning = function(cond) {
  #  message(cond)
  #  pWald <- NaN
  #  return(pWald)
  #}
  #)
  
  #State
  s_ninety <- quantile(res_expectiles$Res$stateVariable, 0.9)
  s_mean <- res_expectiles$AvState
  
  #Put Return value together: return one row vector containing all the results
  res_e <- t(c(lon, lat, theta_1_q, theta_2_q, pvalue, #out,
               s_mean, s_ninety)) 
  
  return(res_e)
}
