#Clear all, Packages, Directory
rm(list=ls())
library(tidyverse)

##Local
#setwd('~/Documents/UNI/Master/Masterarbeit')
##Cluster
setwd('/pfs/imk/imk-tro/Gruppe_Knippertz/bn1998')


#initialize new DataFrame
res_quantiles_mean16 <- data.frame(lon=double(), lat=double(),
                                     theta1=double(), theta2=double(),
                                     p_opt=double(), s_mean=double(),
                                     s_ninety=double(), p_wald=double())
res_expectiles_mean16 <- data.frame(lon=double(), lat=double(),
                                     theta1=double(), theta2=double(),
                                     p_opt=double(), s_mean=double(),
                                     s_ninety=double(), p_wald=double())

#load results generated by ExtractResultsAll and ExtractPWald 
#(now in one file; the p-value vector has been added as a coloumn in both result files)
load('Daten/Ergebnisse/ResultsCompleteInstrumentsLag2/Res_quantiles.Rdata')
load('Daten/Ergebnisse/ResultsCompleteInstrumentsLag2/Res_expectiles.Rdata')

#filter out the points where the covariance matrix has been singular
res_quantiles <- res_quantiles %>% filter(p_wald!='NaN')
res_expectiles <- res_expectiles %>% filter(p_wald!='NaN')

#mean the results
#l geht longitude durch, b latitude

i=1
for (l in seq(-180,179,1)) {
  for (b in seq(-50,49,1)) {
    
    print(i)
    help_matrix_q <- res_quantiles %>% filter(lon > l) %>% filter(lon < l + 1) %>% 
      filter(lat > b) %>% filter(lat<b+1)
    help_matrix_e <- res_expectiles %>% filter(lon > l) %>% filter(lon < l + 1) %>% 
      filter(lat > b) %>% filter(lat<b+1)
    
    res_quantiles_mean16[i,] = c(l+0.5, b+0.5,
                                 mean(help_matrix_q$theta1), mean(help_matrix_q$theta2),
                                 mean(help_matrix_q$p_opt), mean(help_matrix_q$s_mean),
                                 mean(help_matrix_q$s_ninety), mean(help_matrix_q$p_wald))
    res_expectiles_mean16[i,] = c(l+0.5, b+0.5,
                                 mean(help_matrix_e$theta1), mean(help_matrix_e$theta2),
                                 mean(help_matrix_e$p_opt), mean(help_matrix_e$s_mean),
                                 mean(help_matrix_e$s_ninety), mean(help_matrix_e$p_wald))
                        
    i=i+1
    print(i)
  }
}

#save new results
save(res_quantiles_mean16, file='Daten/Ergebnisse/ResultsCompleteInstrumentsLag2/Res_quantiles_mean16.Rdata')
save(res_expectiles_mean16, file='Daten/Ergebnisse/ResultsCompleteInstrumentsLag2/Res_expectiles_mean16.Rdata')

